schema_version: 1

context:
  name: nix
  version: 2.34.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/NixOS/nix/archive/refs/tags/${{ version }}.tar.gz
    sha256: f317b0fd6cba73bf5c05e0fdda7ca4fae163bf28f8566572c5bd288a2f180c8a
    patches:
      - patches/0001-fix-functional-tests-depends-type.patch
      - patches/0002-guard-SYS_close_range-for-old-kernel-headers.patch
      - patches/0003-define-CLONE_NEWCGROUP-for-old-kernel-headers.patch
  - url: https://github.com/BLAKE3-team/BLAKE3/archive/refs/tags/1.8.5.tar.gz
    sha256: 220bd81286e2a0585beac66d41ac3f4c2c33ae8a4e339fc88cf22d5e00514fe9
    target_directory: blake3

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - cmake
    - meson >=1.1
    - ninja
    - bison
    - flex
    - xz-tools
  host:
    - openssl
    - brotli
    - curl
    - sqlite
    - libboost-devel
    - editline
    - zlib
    - libarchive
    - libsodium
    - nlohmann_json
    - libgit2
    - bdw-gc
    - toml11
    - if: linux
      then: libseccomp
  run:
    - brotli
    - libcurl
    - curl
    - editline

tests:
  - package_contents:
      bin:
        - nix
        - nix-build
        - nix-channel
        - nix-collect-garbage
        - nix-copy-closure
        - nix-daemon
        - nix-env
        - nix-hash
        - nix-instantiate
        - nix-prefetch-url
        - nix-shell
        - nix-store
      lib:
        - libnixutil
        - libnixstore
        - libnixexpr
        - libnixmain
  - script:
      - nix --help

about:
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: The Purely Functional Package Manager
  description: |
    Nix is a powerful package manager for Linux and other Unix systems
    that makes package management reliable and reproducible. It provides
    atomic upgrades and rollbacks, side-by-side installation of multiple
    versions of a package, multi-user package management and easy setup
    of build environments.
  homepage: https://nixos.org/nix/
  repository: https://github.com/NixOS/nix
  documentation: https://nixos.org/nix/manual/

extra:
  recipe-maintainers:
    - scopatz
    - phreed
